CREATE INDEX `ix_applications_user` ON `applications` (`userId`);--> statement-breakpoint
CREATE INDEX `ix_applications_status` ON `applications` (`status`);--> statement-breakpoint
CREATE INDEX `ix_attendance_session` ON `attendance` (`sessionId`);--> statement-breakpoint
CREATE INDEX `ix_attendance_member` ON `attendance` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_ballotroll_election_member` ON `ballot_roll` (`electionId`,`memberId`);--> statement-breakpoint
CREATE INDEX `ix_cadencelog_cadence_period` ON `cadence_log` (`cadenceId`,`periodKey`);--> statement-breakpoint
CREATE INDEX `ix_cadences_chapter` ON `cadences` (`chapterId`);--> statement-breakpoint
CREATE INDEX `ix_candidates_election` ON `candidates` (`electionId`);--> statement-breakpoint
CREATE INDEX `ix_chposts_chapter` ON `chapter_posts` (`chapterId`);--> statement-breakpoint
CREATE INDEX `ix_chroles_chapter_status` ON `chapter_roles` (`chapterId`,`status`);--> statement-breakpoint
CREATE INDEX `ix_chroles_member` ON `chapter_roles` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_chtransfers_status` ON `chapter_transfers` (`status`);--> statement-breakpoint
CREATE INDEX `ix_chtransfers_member` ON `chapter_transfers` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_elections_chapter` ON `elections` (`chapterId`);--> statement-breakpoint
CREATE INDEX `ix_endorsements_app` ON `endorsements` (`appId`);--> statement-breakpoint
CREATE INDEX `ix_eventfb_event` ON `event_feedback` (`eventId`);--> statement-breakpoint
CREATE INDEX `ix_eventregs_event_status` ON `event_regs` (`eventId`,`status`);--> statement-breakpoint
CREATE INDEX `ix_eventregs_member` ON `event_regs` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_eventregs_code` ON `event_regs` (`checkinCode`);--> statement-breakpoint
CREATE INDEX `ix_govroles_body` ON `gov_roles` (`bodyId`);--> statement-breakpoint
CREATE INDEX `ix_health_chapter` ON `health_snapshots` (`chapterId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `ix_leads_status` ON `leads` (`status`);--> statement-breakpoint
CREATE INDEX `ix_leads_created` ON `leads` (`createdAt`);--> statement-breakpoint
CREATE INDEX `ix_members_tier_status` ON `members` (`tier`,`status`);--> statement-breakpoint
CREATE INDEX `ix_members_status_score` ON `members` (`status`,`hiveScore`);--> statement-breakpoint
CREATE INDEX `ix_members_home_chapter` ON `members` (`homeChapterId`);--> statement-breakpoint
CREATE INDEX `ix_members_lifecycle` ON `members` (`lifecycleState`);--> statement-breakpoint
CREATE INDEX `ix_membevents_member` ON `membership_events` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_membevents_status` ON `membership_events` (`status`);--> statement-breakpoint
CREATE INDEX `ix_motionvotes_motion_member` ON `motion_votes` (`motionId`,`memberId`);--> statement-breakpoint
CREATE INDEX `ix_motions_chapter` ON `motions` (`chapterId`);--> statement-breakpoint
CREATE INDEX `ix_notifications_member_read` ON `notifications` (`memberId`,`readAt`);--> statement-breakpoint
CREATE INDEX `ix_o2o_a` ON `one_to_ones` (`aMemberId`);--> statement-breakpoint
CREATE INDEX `ix_o2o_b` ON `one_to_ones` (`bMemberId`);--> statement-breakpoint
CREATE INDEX `ix_referrals_member` ON `referrals` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_scoreevents_member` ON `score_events` (`memberId`);--> statement-breakpoint
CREATE INDEX `ix_sessions_pod_starts` ON `sessions` (`podId`,`startsAt`);