import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    /* Vendored shadcn/ui primitives are generated by the shadcn CLI: they
       co-export `*Variants` helpers alongside components (react-refresh), use
       `any` in a few forwarded-prop signatures, and seed a random skeleton
       width (purity). These are library files, not hand-authored app code, so
       relax the rules that only flag those generated patterns. */
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'react-hooks/purity': 'off',
    },
  },
  {
    /* eh.tsx is the app's shared component + helper kit and trpc.tsx is the
       tRPC provider module — both legitimately export helpers/objects next to
       components, which is all the react-refresh rule flags here. */
    files: ['src/components/eh.tsx', 'src/providers/trpc.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
